name: 'Arcanist Lint'
description: 'Arcanist lint checker'
author: 'Sharon (Sean) Rolel'
inputs:
  arc_path:
    description: 'Path to arc'
    required: false
    default: 'arc'
  arguments:
    description: 'Extra arguments (file paths etc.)'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
